### ISSUE TITLE
Not recognizing API Key

### ISSUE THREAD

**Issue by countvidal** [itzmestar/Messari#3]
Looks like its getting rate limited and not recognizing api key.

**Comment by itzmestar** [comment]
Can you please provide more details?

**Comment by countvidal** [comment]
I innitialized it with an api key: messari = Messari(key='my_key_here'), I then run a loop to get the historic info for like 600 coins, api errors out at around 20 requests per second.

**Comment by countvidal** [comment]
I then go to messari and try to see the recent activity of the API key and it doesn't show any history. It doesnt seem that the messari API endpoints is recognizing that an API key is being sent.

**Comment by countvidal** [comment]
Managed to fix it, was using wrong API key looks like haha. Thanks

**Comment by itzmestar** [comment]
That's good.  if you like the library, please show the support by giving a star. :)
